services:
  grocy:
    image: lscr.io/linuxserver/grocy:latest
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: America/Denver
    volumes:
      - ${PLATFORM_CONFIG_ROOT}/grocy:/config
    networks:
      - internal
