all:
  children:
    homelab:
      hosts:
        chase-raspberrypi:
          ansible_host: chase-raspberrypi.local
          ansible_user: chaseconover
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
